-- ── Cincinnati Open 2026 — player_stats seed for server-side validation + scoring ────────────────
-- WHY ALL FOUR COLUMNS: save_entry validates the TIER QUOTA off player_stats.tier and the BUDGET off
-- .price, and recompute-score reads .ranking for the upset multiplier. A row carrying only `ranking`
-- leaves tier/price NULL — the quota check then reads a legal 2/3/5 squad as 2/3/4 (so it can never
-- be locked) and sum(price) silently under-counts the budget. Every drafted player needs all four.
--
-- Generated by scripts/gen-seed.mjs from src/data/cincinnati2026Field.json (built from the published draw and reconciled
-- against Wikipedia: 0 missing, 0 phantom). 96 players.
--
-- SAFE TO RUN ANY TIME, INCLUDING WHILE ANOTHER EVENT IS STILL BEING SCORED: the generator verifies
-- that every player shared with an existing seed (70 of them) carries an IDENTICAL rank, price
-- and tier — so this only ADDS the 26 players new to this event and cannot
-- retroactively alter a past score. The upsert keeps it re-runnable.
--
-- Regenerate with:  node scripts/gen-seed.mjs cincinnati_2026

insert into public.player_stats (id, ranking, price, tier) values
  ('zverev', 3, 50, 'Platinum'),
  ('augeraliassime', 4, 34, 'Platinum'),
  ('djokovic', 5, 37, 'Platinum'),
  ('shelton', 6, 31, 'Platinum'),
  ('medvedev', 7, 34, 'Platinum'),
  ('deminaur', 8, 25, 'Platinum'),
  ('fritz', 9, 23, 'Platinum'),
  ('cobolli', 10, 18, 'Platinum'),
  ('jodar', 11, 24, 'Gold'),
  ('tien', 12, 22, 'Gold'),
  ('lehecka', 14, 19, 'Gold'),
  ('musetti', 15, 19, 'Gold'),
  ('mensik', 16, 20, 'Gold'),
  ('ruud', 17, 17, 'Gold'),
  ('rublev', 18, 17, 'Gold'),
  ('vacherot', 19, 14, 'Gold'),
  ('darderi', 20, 16, 'Gold'),
  ('fils', 21, 18, 'Gold'),
  ('nakashima', 22, 16, 'Gold'),
  ('tiafoe', 23, 16, 'Gold'),
  ('paul', 24, 15, 'Gold'),
  ('franciscocerundolo', 25, 15, 'Gold'),
  ('fonseca', 26, 14, 'Silver'),
  ('rinderknech', 28, 12, 'Silver'),
  ('tabilo', 29, 11, 'Silver'),
  ('humbert', 30, 12, 'Silver'),
  ('etcheverry', 31, 10, 'Silver'),
  ('blockx', 32, 11, 'Silver'),
  ('bergs', 33, 11, 'Silver'),
  ('arnaldi', 34, 10, 'Silver'),
  ('norrie', 35, 12, 'Silver'),
  ('buse', 36, 12, 'Silver'),
  ('fery', 37, 13, 'Silver'),
  ('collignon', 38, 10, 'Silver'),
  ('khachanov', 39, 10, 'Silver'),
  ('merida', 40, 12, 'Silver'),
  ('michelsen', 41, 12, 'Silver'),
  ('berrettini', 42, 10, 'Silver'),
  ('struff', 43, 7, 'Silver'),
  ('navone', 44, 8, 'Silver'),
  ('atmane', 45, 9, 'Silver'),
  ('borges', 47, 10, 'Silver'),
  ('shapovalov', 48, 7, 'Silver'),
  ('tsitsipas', 49, 9, 'Silver'),
  ('tirante', 50, 10, 'Silver'),
  ('cerundolo', 51, 9, 'Silver'),
  ('mannarino', 52, 6, 'Silver'),
  ('baez', 53, 10, 'Silver'),
  ('assche', 54, 5, 'Silver'),
  ('hanfmann', 55, 9, 'Silver'),
  ('griekspoor', 56, 9, 'Silver'),
  ('halys', 57, 10, 'Silver'),
  ('zandschulp', 59, 9, 'Silver'),
  ('burruchaga', 61, 5, 'Silver'),
  ('machac', 62, 11, 'Silver'),
  ('marozsan', 63, 8, 'Silver'),
  ('altmaier', 65, 6, 'Silver'),
  ('kecmanovic', 66, 6, 'Silver'),
  ('landaluce', 67, 9, 'Silver'),
  ('majchrzak', 68, 8, 'Silver'),
  ('hurkacz', 69, 7, 'Silver'),
  ('vallejo', 70, 6, 'Silver'),
  ('kopriva', 71, 8, 'Silver'),
  ('busta', 72, 8, 'Silver'),
  ('medjedovic', 73, 8, 'Silver'),
  ('brooksby', 74, 7, 'Silver'),
  ('carabelli', 76, 6, 'Silver'),
  ('choinski', 77, 8, 'Silver'),
  ('royer', 78, 5, 'Silver'),
  ('faria', 79, 6, 'Silver'),
  ('cilic', 80, 7, 'Silver'),
  ('bellucci', 81, 6, 'Silver'),
  ('fucsovics', 82, 6, 'Silver'),
  ('svajda', 84, 7, 'Silver'),
  ('duckworth', 86, 6, 'Silver'),
  ('sonego', 88, 6, 'Silver'),
  ('shimabukuro', 90, 7, 'Silver'),
  ('trungelliti', 91, 5, 'Silver'),
  ('wong', 93, 6, 'Silver'),
  ('hijikata', 95, 8, 'Silver'),
  ('kovacevic', 96, 6, 'Silver'),
  ('walton', 98, 6, 'Silver'),
  ('prizmic', 103, 8, 'Silver'),
  ('jong', 106, 6, 'Silver'),
  ('droguet', 115, 7, 'Silver'),
  ('zheng', 121, 5, 'Silver'),
  ('connell', 127, 5, 'Silver'),
  ('jacquet', 134, 5, 'Silver'),
  ('mejia', 136, 5, 'Silver'),
  ('dimitrov', 142, 5, 'Silver'),
  ('draper', 147, 6, 'Silver'),
  ('lajal', 150, 5, 'Silver'),
  ('shang', 270, 4, 'Silver'),
  ('monfils', 327, 4, 'Silver'),
  ('kokkinakis', 443, 4, 'Silver'),
  ('wolf', 688, 4, 'Silver')
on conflict (id) do update set ranking = excluded.ranking, price = excluded.price, tier = excluded.tier;

-- Verify: every entrant has a COMPLETE row (a NULL price or tier is the bug described above).
-- select count(*) filter (where price is not null and tier is not null) as complete,
--        count(*) filter (where price is null or tier is null)         as broken
--   from public.player_stats;
