-- ── Cincinnati Open 2026 — player_stats seed for server-side validation + scoring ────────────────
-- WHY ALL FOUR COLUMNS: save_entry validates the TIER QUOTA off player_stats.tier and the BUDGET off
-- .price, and recompute-score reads .ranking for the upset multiplier. A row carrying only `ranking`
-- leaves tier/price NULL — the quota check then reads a legal 2/3/5 squad as 2/3/4 (so it can never
-- be locked) and sum(price) silently under-counts the budget. Every drafted player needs all four.
--
-- Generated by scripts/gen-seed.mjs from src/data/cincinnati2026Field.json (built from the published draw and reconciled
-- against Wikipedia: 0 missing, 0 phantom). 96 players.
--
-- SAFE TO RUN ANY TIME, INCLUDING WHILE ANOTHER EVENT IS STILL BEING SCORED: the generator verifies
-- that every player shared with an existing seed (70 of them) carries an IDENTICAL rank, price
-- and tier — so this only ADDS the 26 players new to this event and cannot
-- retroactively alter a past score. The upsert keeps it re-runnable.
--
-- Regenerate with:  node scripts/gen-seed.mjs cincinnati_2026

insert into public.player_stats (tournament_id, id, ranking, price, tier) values
  ('cincinnati_2026', 'zverev', 3, 50, 'Platinum'),
  ('cincinnati_2026', 'augeraliassime', 4, 34, 'Platinum'),
  ('cincinnati_2026', 'djokovic', 5, 37, 'Platinum'),
  ('cincinnati_2026', 'shelton', 6, 31, 'Platinum'),
  ('cincinnati_2026', 'medvedev', 7, 34, 'Platinum'),
  ('cincinnati_2026', 'deminaur', 8, 25, 'Platinum'),
  ('cincinnati_2026', 'fritz', 9, 23, 'Platinum'),
  ('cincinnati_2026', 'cobolli', 10, 18, 'Platinum'),
  ('cincinnati_2026', 'jodar', 11, 24, 'Gold'),
  ('cincinnati_2026', 'tien', 12, 22, 'Gold'),
  ('cincinnati_2026', 'lehecka', 14, 19, 'Gold'),
  ('cincinnati_2026', 'musetti', 15, 19, 'Gold'),
  ('cincinnati_2026', 'mensik', 16, 20, 'Gold'),
  ('cincinnati_2026', 'ruud', 17, 17, 'Gold'),
  ('cincinnati_2026', 'rublev', 18, 17, 'Gold'),
  ('cincinnati_2026', 'vacherot', 19, 14, 'Gold'),
  ('cincinnati_2026', 'darderi', 20, 16, 'Gold'),
  ('cincinnati_2026', 'fils', 21, 18, 'Gold'),
  ('cincinnati_2026', 'nakashima', 22, 16, 'Gold'),
  ('cincinnati_2026', 'tiafoe', 23, 16, 'Gold'),
  ('cincinnati_2026', 'paul', 24, 15, 'Gold'),
  ('cincinnati_2026', 'franciscocerundolo', 25, 15, 'Gold'),
  ('cincinnati_2026', 'fonseca', 26, 14, 'Silver'),
  ('cincinnati_2026', 'rinderknech', 28, 12, 'Silver'),
  ('cincinnati_2026', 'tabilo', 29, 11, 'Silver'),
  ('cincinnati_2026', 'humbert', 30, 12, 'Silver'),
  ('cincinnati_2026', 'etcheverry', 31, 10, 'Silver'),
  ('cincinnati_2026', 'blockx', 32, 11, 'Silver'),
  ('cincinnati_2026', 'bergs', 33, 11, 'Silver'),
  ('cincinnati_2026', 'arnaldi', 34, 10, 'Silver'),
  ('cincinnati_2026', 'norrie', 35, 12, 'Silver'),
  ('cincinnati_2026', 'buse', 36, 12, 'Silver'),
  ('cincinnati_2026', 'fery', 37, 13, 'Silver'),
  ('cincinnati_2026', 'collignon', 38, 10, 'Silver'),
  ('cincinnati_2026', 'khachanov', 39, 10, 'Silver'),
  ('cincinnati_2026', 'merida', 40, 12, 'Silver'),
  ('cincinnati_2026', 'michelsen', 41, 12, 'Silver'),
  ('cincinnati_2026', 'berrettini', 42, 10, 'Silver'),
  ('cincinnati_2026', 'struff', 43, 7, 'Silver'),
  ('cincinnati_2026', 'navone', 44, 8, 'Silver'),
  ('cincinnati_2026', 'atmane', 45, 9, 'Silver'),
  ('cincinnati_2026', 'borges', 47, 10, 'Silver'),
  ('cincinnati_2026', 'shapovalov', 48, 7, 'Silver'),
  ('cincinnati_2026', 'tsitsipas', 49, 9, 'Silver'),
  ('cincinnati_2026', 'tirante', 50, 10, 'Silver'),
  ('cincinnati_2026', 'cerundolo', 51, 9, 'Silver'),
  ('cincinnati_2026', 'mannarino', 52, 6, 'Silver'),
  ('cincinnati_2026', 'baez', 53, 10, 'Silver'),
  ('cincinnati_2026', 'assche', 54, 5, 'Silver'),
  ('cincinnati_2026', 'hanfmann', 55, 9, 'Silver'),
  ('cincinnati_2026', 'griekspoor', 56, 9, 'Silver'),
  ('cincinnati_2026', 'halys', 57, 10, 'Silver'),
  ('cincinnati_2026', 'zandschulp', 59, 9, 'Silver'),
  ('cincinnati_2026', 'burruchaga', 61, 5, 'Silver'),
  ('cincinnati_2026', 'machac', 62, 11, 'Silver'),
  ('cincinnati_2026', 'marozsan', 63, 8, 'Silver'),
  ('cincinnati_2026', 'altmaier', 65, 6, 'Silver'),
  ('cincinnati_2026', 'kecmanovic', 66, 6, 'Silver'),
  ('cincinnati_2026', 'landaluce', 67, 9, 'Silver'),
  ('cincinnati_2026', 'majchrzak', 68, 8, 'Silver'),
  ('cincinnati_2026', 'hurkacz', 69, 7, 'Silver'),
  ('cincinnati_2026', 'vallejo', 70, 6, 'Silver'),
  ('cincinnati_2026', 'kopriva', 71, 8, 'Silver'),
  ('cincinnati_2026', 'busta', 72, 8, 'Silver'),
  ('cincinnati_2026', 'medjedovic', 73, 8, 'Silver'),
  ('cincinnati_2026', 'brooksby', 74, 7, 'Silver'),
  ('cincinnati_2026', 'carabelli', 76, 6, 'Silver'),
  ('cincinnati_2026', 'choinski', 77, 8, 'Silver'),
  ('cincinnati_2026', 'royer', 78, 5, 'Silver'),
  ('cincinnati_2026', 'faria', 79, 6, 'Silver'),
  ('cincinnati_2026', 'cilic', 80, 7, 'Silver'),
  ('cincinnati_2026', 'bellucci', 81, 6, 'Silver'),
  ('cincinnati_2026', 'fucsovics', 82, 6, 'Silver'),
  ('cincinnati_2026', 'svajda', 84, 7, 'Silver'),
  ('cincinnati_2026', 'duckworth', 86, 6, 'Silver'),
  ('cincinnati_2026', 'sonego', 88, 6, 'Silver'),
  ('cincinnati_2026', 'shimabukuro', 90, 7, 'Silver'),
  ('cincinnati_2026', 'trungelliti', 91, 5, 'Silver'),
  ('cincinnati_2026', 'wong', 93, 6, 'Silver'),
  ('cincinnati_2026', 'hijikata', 95, 8, 'Silver'),
  ('cincinnati_2026', 'kovacevic', 96, 6, 'Silver'),
  ('cincinnati_2026', 'walton', 98, 6, 'Silver'),
  ('cincinnati_2026', 'prizmic', 103, 8, 'Silver'),
  ('cincinnati_2026', 'jong', 106, 6, 'Silver'),
  ('cincinnati_2026', 'droguet', 115, 7, 'Silver'),
  ('cincinnati_2026', 'zheng', 121, 5, 'Silver'),
  ('cincinnati_2026', 'connell', 127, 5, 'Silver'),
  ('cincinnati_2026', 'jacquet', 134, 5, 'Silver'),
  ('cincinnati_2026', 'mejia', 136, 5, 'Silver'),
  ('cincinnati_2026', 'dimitrov', 142, 5, 'Silver'),
  ('cincinnati_2026', 'draper', 147, 6, 'Silver'),
  ('cincinnati_2026', 'lajal', 150, 5, 'Silver'),
  ('cincinnati_2026', 'shang', 270, 4, 'Silver'),
  ('cincinnati_2026', 'monfils', 327, 4, 'Silver'),
  ('cincinnati_2026', 'kokkinakis', 443, 4, 'Silver'),
  ('cincinnati_2026', 'wolf', 688, 4, 'Silver')
on conflict (tournament_id, id) do update set ranking = excluded.ranking, price = excluded.price, tier = excluded.tier;

-- Verify: every entrant has a COMPLETE row (a NULL price or tier is the bug described above).
-- select count(*) filter (where price is not null and tier is not null) as complete,
--        count(*) filter (where price is null or tier is null)         as broken
--   from public.player_stats;
