// ── Generate a tournament's player_stats seed (id, ranking, price, tier) ─────────────────────────
// WHY ALL FOUR COLUMNS: save_entry validates the TIER QUOTA off player_stats.tier and the BUDGET off
// .price, and recompute-score reads .ranking for the upset multiplier. A row carrying only `ranking`
// leaves tier/price NULL — the quota check then reads a legal 2/3/5 squad as 2/3/4 (so it can never
// be locked) and sum(price) silently under-counts the budget. This bit us at the Cincinnati cutover:
// 14 entrants incl. Djokovic and Draper would have been impossible to lock into a squad.
//
//   node scripts/gen-seed.mjs cincinnati_2026            # write the seed
//   node scripts/gen-seed.mjs cincinnati_2026 --check    # verify only; non-zero exit if stale
//
// player_stats is ONE table shared by every event, so the generator CROSS-CHECKS: any player this
// event shares with an already-written seed must come out at an identical rank/price/tier, or the
// two seeds would fight and applying this one could retroactively change a past score.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { EVENTS, getEvent } from './lib/events.mjs';
import { tierOf, priceOf } from './lib/pricing.mjs';

const [id, ...flags] = process.argv.slice(2);
if (!id) { console.error('usage: node scripts/gen-seed.mjs <event-id> [--check]'); process.exit(2); }
const CHECK = flags.includes('--check');
const ev = getEvent(id);
const root = new URL('../', import.meta.url);

const field = JSON.parse(readFileSync(new URL(ev.field, root), 'utf8'));
const rows = field.map(p => ({
  id: p.id,
  ranking: p.ranking,
  price: priceOf(p.ranking, p.ytd, p.surface?.[ev.surface]),
  tier: tierOf(p.ranking),
})).sort((a, b) => a.ranking - b.ranking);

// ── Cross-check against every OTHER seed already in the repo ─────────────────────────────────────
const others = [
  // save_entry_rpc.sql used to be listed here — it carried an embedded 77-row seed. That block is
  // gone (it held 7 players who are not in the Cincinnati draw); seeds now live only in their own
  // per-event files, which is the only place this cross-check should ever have been reading.
  ...Object.entries(EVENTS).filter(([k]) => k !== id).map(([, e]) => e.seed),
];
const seen = new Map();   // id → { ranking, price, tier, from }
for (const rel of others) {
  const url = new URL(rel, root);
  if (!existsSync(url)) continue;
  const sql = readFileSync(url, 'utf8');
  for (const m of sql.matchAll(/\(\s*'([a-z0-9_]+)'\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*'(\w+)'\s*\)/g)) {
    if (!seen.has(m[1])) seen.set(m[1], { ranking: +m[2], price: +m[3], tier: m[4], from: rel });
  }
}
const clashes = rows.filter(r => {
  const o = seen.get(r.id);
  return o && (o.ranking !== r.ranking || o.price !== r.price || o.tier !== r.tier);
});
const shared = rows.filter(r => seen.has(r.id)).length;

console.log(`\n  event:            ${id} — ${ev.label}`);
console.log(`  field:            ${rows.length} players`);
console.log(`  shared with existing seeds: ${shared}   mismatches: ${clashes.length}`);
for (const c of clashes) {
  const o = seen.get(c.id);
  console.log(`    ✗ ${c.id}: ${o.from} has rank ${o.ranking} $${o.price} ${o.tier} — this event says ${c.ranking} $${c.price} ${c.tier}`);
}
// NOT an error since fix 1.3. player_stats is keyed (tournament_id, id), so each event owns its own
// rows: a differing rank or price just means the player moved between tournaments, which is exactly
// what scoping exists to record. Reported for eyeballing. It used to exit 1 because, with one shared
// table, a clash would have silently rewritten a finished event's scores.
if (clashes.length) {
  console.log(`
  note: ${clashes.length} player(s) differ from an earlier seed — expected; each event keeps its own row.
`);
}
{
  const body = rows.map(r => `  ('${id}', '${r.id}', ${r.ranking}, ${r.price}, '${r.tier}')`).join(',\n');
  const sql = `-- ── ${ev.label} — player_stats seed for server-side validation + scoring ────────────────
-- WHY ALL FOUR COLUMNS: save_entry validates the TIER QUOTA off player_stats.tier and the BUDGET off
-- .price, and recompute-score reads .ranking for the upset multiplier. A row carrying only \`ranking\`
-- leaves tier/price NULL — the quota check then reads a legal 2/3/5 squad as 2/3/4 (so it can never
-- be locked) and sum(price) silently under-counts the budget. Every drafted player needs all four.
--
-- Generated by scripts/gen-seed.mjs from ${ev.field} (built from the published draw and reconciled
-- against Wikipedia: 0 missing, 0 phantom). ${rows.length} players.
--
-- SAFE TO RUN ANY TIME, INCLUDING WHILE ANOTHER EVENT IS STILL BEING SCORED: the generator verifies
-- that every player shared with an existing seed (${shared} of them) carries an IDENTICAL rank, price
-- and tier — so this only ADDS the ${rows.length - shared} players new to this event and cannot
-- retroactively alter a past score. The upsert keeps it re-runnable.
--
-- Regenerate with:  node scripts/gen-seed.mjs ${id}

insert into public.player_stats (tournament_id, id, ranking, price, tier) values
${body}
on conflict (tournament_id, id) do update set ranking = excluded.ranking, price = excluded.price, tier = excluded.tier;

-- Verify: every entrant has a COMPLETE row (a NULL price or tier is the bug described above).
-- select count(*) filter (where price is not null and tier is not null) as complete,
--        count(*) filter (where price is null or tier is null)         as broken
--   from public.player_stats;
`;
  const out = new URL(ev.seed, root);
  if (CHECK) {
    const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
    if (current.trim() !== sql.trim()) { console.error(`\n  ✗ ${ev.seed} is out of date — re-run without --check\n`); process.exitCode = 1; }
    else console.log(`\n  ✓ ${ev.seed} is up to date\n`);
  } else {
    writeFileSync(out, sql);
    console.log(`\n  ✓ wrote ${rows.length} rows → ${ev.seed}`);
    console.log(`    (${rows.length - shared} new to this event, ${shared} identical to existing seeds)\n`);
  }
}
